<?php

use Illuminate\Database\Seeder;
use  Illuminate\Support\Facades\DB;

class DiallingCodeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('dialling_codes')->insert(
            [
                ['dialling_code' => 1403, 'name' => 'Alberta, Canada'],
                ['dialling_code' => 1587, 'name' => 'Alberta,Canada'],
                ['dialling_code' => 1780, 'name' => 'Alberta,Canada'],
                ['dialling_code' => 1250, 'name' => 'British Columbia,Canada'],
                ['dialling_code' => 1604, 'name' => 'British Columbia,Canada'],
                ['dialling_code' => 1778, 'name' => 'British Columbia,Canada'],
                ['dialling_code' => 1236, 'name' => 'British Columbia,Canada'],
                ['dialling_code' => 1204, 'name' => 'Manitoba,Canada'],
                ['dialling_code' => 1431, 'name' => 'Manitoba, Canada'],
                ['dialling_code' => 1506, 'name' => 'New Brunswick,Canada'],
                ['dialling_code' => 1709, 'name' => 'Newfoundland and Labrador, Canada'],
                ['dialling_code' => 1902, 'name' => 'Nova Scotia and Prince Edward Islands, Canada'],
                ['dialling_code' => 1782, 'name' => 'Nova Scotia and Prince Edward Islands, Canada'],
                ['dialling_code' => 1226, 'name' => 'Ontario, Canada'],
                ['dialling_code' => 1249, 'name' => 'Ontario, Canada'],
                ['dialling_code' => 1289, 'name' => 'Ontario, Canada'],
                ['dialling_code' => 1343, 'name' => 'Ontario, Canada'],
                ['dialling_code' => 1416, 'name' => 'Ontario, Canada'],
                ['dialling_code' => 1519, 'name' => 'Ontario, Canada'],
                ['dialling_code' => 1613, 'name' => 'Ontario, Canada'],
                ['dialling_code' => 1647, 'name' => 'Ontario, Canada'],
                ['dialling_code' => 1705, 'name' => 'Ontario, Canada'],
                ['dialling_code' => 1807, 'name' => 'Ontario, Canada'],
                ['dialling_code' => 1905, 'Ontario, Canada'],
                ['dialling_code' => 1418, 'name' => 'Quebec, Canada'],
                ['dialling_code' => 1438, 'name' => 'Quebec, Canada'],
                ['dialling_code' => 1450, 'name' => 'Quebec, Canada'],
                ['dialling_code' => 1514, 'name' => 'Quebec, Canada'],
                ['dialling_code' => 1579, 'name' => 'Quebec, Canada'],
                ['dialling_code' => 1581, 'name' => 'Quebec, Canada'],
                ['dialling_code' => 1819, 'name' => 'Quebec, Canada'],
                ['dialling_code' => 1873, 'name' => 'Quebec, Canada'],
                ['dialling_code' => 1306, 'name' => 'Saskatchewan,Canada'],
                ['dialling_code' => 1639, 'name' => 'Saskatchewan,Canada'],
                ['dialling_code' => 1867, 'name' => 'Yukon,Northwest Territories and Nunavut,Canada'],
                ['dialling_code' => 1242, 'name' => 'Bahamas'],
                ['dialling_code' => 1264, 'name' => 'Anguilla'],
                ['dialling_code' => 1268, 'name' => 'Antiqua and Barbuda'],
                ['dialling_code' => 1284, 'name' => 'British Virgin Islands'],
                ['dialling_code' => 1345, 'name' => 'Cayman Islands'],
                ['dialling_code' => 1441, 'name' => 'Bermuda'],
                ['dialling_code' => 1473, 'name' => 'Grenada'],
                ['dialling_code' => 1617, 'name' => 'Guam'],
                ['dialling_code' => 1684, 'name' => 'American Samoa'],
                ['dialling_code' => 1721, 'name' => 'Sint Maarten'],
                ['dialling_code' => 1758, 'name' => 'Saint Lucia'],
                ['dialling_code' => 1767, 'name' => 'Dominica'],
                ['dialling_code' => 1787, 'name' => 'Puerto Rico'],
                ['dialling_code' => 1809, 'name' => 'Dominican Republic'],
                ['dialling_code' => 1829, 'name' => 'Dominican Republic'],
                ['dialling_code' => 1849, 'name' => 'Dominican Republic'],
                ['dialling_code' => 1868, 'name' => 'Trinidad and Tobago'],
                ['dialling_code' => 1876, 'name' => 'Jamaica'],
                ['dialling_code' => 1, 'name' => 'United States'],
                ['dialling_code' => 25524, 'name' => 'Zanzibar in Tanzania'],
                ['dialling_code' => 211, 'name' => 'South Sudan'],
                ['dialling_code' => 212, 'name' => 'Morocco'],
                ['dialling_code' => 213, 'name' => 'Algeria'],
                ['dialling_code' => 216, 'name' => 'Tunisia'],
                ['dialling_code' => 218, 'name' => 'Libya'],
                ['dialling_code' => 221, 'name' => 'Senegal'],
                ['dialling_code' => 222, 'name' => 'Mauritania'],
                ['dialling_code' => 223, 'name' => 'Mali'],
                ['dialling_code' => 224, 'name' => 'Guinea'],
                ['dialling_code' => 225, 'name' => 'Côte d\'Ivoire'],
                ['dialling_code' => 226, 'name' => 'Burkina Faso'],
                ['dialling_code' => 227, 'name' => 'Niger'],
                ['dialling_code' => 228, 'name' => 'Togo'],
                ['dialling_code' => 229, 'name' => 'Benin'],
                ['dialling_code' => 230, 'name' => 'Mauritius'],
                ['dialling_code' => 231, 'name' => 'Liberia'],
                ['dialling_code' => 232, 'name' => 'Sierra Leone'],
                ['dialling_code' => 233, 'name' => 'Ghana'],
                ['dialling_code' => 234, 'name' => 'Nigeria'],
                ['dialling_code' => 235, 'name' => 'Chad'],
                ['dialling_code' => 236, 'name' => 'Central African Republic'],
                ['dialling_code' => 237, 'name' => 'Cameroon'],
                ['dialling_code' => 238, 'name' => 'Cape Verde'],
                ['dialling_code' => 241, 'name' => 'Gabon'],
                ['dialling_code' => 242, 'name' => 'Republic of the Congo'],
                ['dialling_code' => 243, 'name' => 'Democratic Republic of the Congo'],
                ['dialling_code' => 244, 'name' => 'Angola'],
                ['dialling_code' => 245, 'name' => 'Guinea-Bissau'],
                ['dialling_code' => 246, 'name' => 'British Indian Ocean Territory'],
                ['dialling_code' => 248, 'name' => 'Seychelles'],
                ['dialling_code' => 249, 'name' => 'Sudan'],
                ['dialling_code' => 250, 'name' => 'Rwanda'],
                ['dialling_code' => 251, 'name' => 'Ethiopia'],
                ['dialling_code' => 254, 'name' => 'Kenya'],
                ['dialling_code' => 255, 'name' => 'Tanzania'],
                ['dialling_code' => 256, 'name' => 'Uganda'],
                ['dialling_code' => 257, 'name' => 'Burundi'],
                ['dialling_code' => 258, 'name' => 'Mozambique'],
                ['dialling_code' => 260, 'name' => 'Zambia'],
                ['dialling_code' => 261, 'name' => 'Madagascar'],
                ['dialling_code' => 263, 'name' => 'Zimbabwe'],
                ['dialling_code' => 264, 'name' => 'Namibia'],
                ['dialling_code' => 265, 'name' => 'Malawi'],
                ['dialling_code' => 266, 'name' => 'Lesotho'],
                ['dialling_code' => 267, 'name' => 'Botswana'],
                ['dialling_code' => 268, 'name' => 'Swaziland'],
                ['dialling_code' => 269, 'name' => 'Comoros'],
                ['dialling_code' => 297, 'name' => 'Aruba'],
                ['dialling_code' => 299, 'name' => 'Greenland'],
                ['dialling_code' => 20, 'name' => 'Egypt'],
                ['dialling_code' => 27, 'name' => 'South Africa'],
                ['dialling_code' => 441534, 'name' => 'Jersey'],
                ['dialling_code' => 37744, 'name' => 'Kosovo'],
                ['dialling_code' => 37745, 'name' => 'Kosovo'],
                ['dialling_code' => 351, 'name' => 'Portugal'],
                ['dialling_code' => 352, 'name' => 'Luxembourg'],
                ['dialling_code' => 353, 'name' => 'Ireland'],
                ['dialling_code' => 354, 'name' => 'Iceland'],
                ['dialling_code' => 355, 'name' => 'Albania'],
                ['dialling_code' => 356, 'name' => 'Malta'],
                ['dialling_code' => 357, 'name' => 'Cyprus'],
                ['dialling_code' => 358, 'name' => 'Finland'],
                ['dialling_code' => 359, 'name' => 'Bulgaria'],
                ['dialling_code' => 370, 'name' => 'Lithuania'],
                ['dialling_code' => 371, 'name' => 'Latvia'],
                ['dialling_code' => 372, 'name' => 'Estonia'],
                ['dialling_code' => 373, 'name' => 'Moldova'],
                ['dialling_code' => 374, 'name' => 'Armenia'],
                ['dialling_code' => 375, 'name' => 'Belarus'],
                ['dialling_code' => 376, 'name' => 'Andorra'],
                ['dialling_code' => 377, 'name' => 'Monaco'],
                ['dialling_code' => 378, 'name' => 'San Marino'],
                ['dialling_code' => 380, 'name' => 'Ukraine'],
                ['dialling_code' => 381, 'name' => 'Serbia'],
                ['dialling_code' => 382, 'name' => 'Montenegro'],
                ['dialling_code' => 385, 'name' => 'Croatia'],
                ['dialling_code' => 386, 'name' => 'Slovenia'],
                ['dialling_code' => 387, 'name' => 'Bosnia and Herzegovina'],
                ['dialling_code' => 389, 'name' => 'Macedonia'],
                ['dialling_code' => 420, 'name' => 'Czech Republic'],
                ['dialling_code' => 421, 'name' => 'Slovakia'],
                ['dialling_code' => 423, 'name' => 'Liechtenstein'],
                ['dialling_code' => 43, 'name' => 'Austria'],
                ['dialling_code' => 44, 'name' => 'United Kingdom'],
                ['dialling_code' => 45, 'name' => 'Denmark'],
                ['dialling_code' => 46, 'name' => 'Sweden'],
                ['dialling_code' => 467, 'name' => 'Sweden'],
                ['dialling_code' => 47, 'name' => 'Norway'],
                ['dialling_code' => 48, 'name' => 'Poland'],
                ['dialling_code' => 49, 'name' => 'Germany'],
                ['dialling_code' => 30, 'name' => 'Greece'],
                ['dialling_code' => 31, 'name' => 'Netherlands'],
                ['dialling_code' => 32, 'name' => 'Belgium'],
                ['dialling_code' => 33, 'name' => 'France'],
                ['dialling_code' => 336, 'name' => 'France'],
                ['dialling_code' => 34, 'name' => 'Spain'],
                ['dialling_code' => 36, 'name' => 'Hungary'],
                ['dialling_code' => 39, 'name' => 'Italy'],
                ['dialling_code' => 40, 'name' => 'Romania'],
                ['dialling_code' => 41, 'name' => 'Switzerland'],
                ['dialling_code' => 501, 'name' => 'Belize'],
                ['dialling_code' => 502, 'name' => 'Guatemala'],
                ['dialling_code' => 504, 'name' => 'Honduras'],
                ['dialling_code' => 505, 'name' => 'Nicaragua'],
                ['dialling_code' => 506, 'name' => 'Costa Rica'],
                ['dialling_code' => 507, 'name' => 'Panama'],
                ['dialling_code' => 509, 'name' => 'Haiti'],
                ['dialling_code' => 591, 'name' => 'Bolivia'],
                ['dialling_code' => 592, 'name' => 'Guyana'],
                ['dialling_code' => 593, 'name' => 'Ecuador'],
                ['dialling_code' => 595, 'name' => 'Paraguay'],
                ['dialling_code' => 596, 'name' => 'Martinique'],
                ['dialling_code' => 597, 'name' => 'Suriname'],
                ['dialling_code' => 598, 'name' => 'Uruguay'],
                ['dialling_code' => 51, 'name' => 'Peru'],
                ['dialling_code' => 52, 'name' => 'Mexico'],
                ['dialling_code' => 53, 'name' => 'Cuba '],
                ['dialling_code' => 54, 'name' => 'Argentina'],
                ['dialling_code' => 55, 'name' => 'Brazil'],
                ['dialling_code' => 56, 'name' => 'Chile'],
                ['dialling_code' => 57, 'name' => 'Colombia'],
                ['dialling_code' => 58, 'name' => 'Venezuela'],
                ['dialling_code' => 60, 'name' => 'Malaysia'],
                ['dialling_code' => 61, 'name' => 'Australia'],
                ['dialling_code' => 62, 'name' => 'Indonesia'],
                ['dialling_code' => 63, 'name' => 'Philippines'],
                ['dialling_code' => 64, 'name' => 'New Zealand'],
                ['dialling_code' => 65, 'name' => 'Singapore'],
                ['dialling_code' => 66, 'name' => 'Thailand'],
                ['dialling_code' => 76, 'name' => 'Kazakhstan'],
                ['dialling_code' => 77, 'name' => 'Kazakhstan'],
                ['dialling_code' => 7, 'name' => 'Russia + terroritoes'],
                ['dialling_code' => 852, 'name' => 'Hong Kong'],
                ['dialling_code' => 853, 'name' => 'Macau'],
                ['dialling_code' => 855, 'name' => 'Cambodia'],
                ['dialling_code' => 856, 'name' => 'Laos'],
                ['dialling_code' => 880, 'name' => 'Bangladesh'],
                ['dialling_code' => 886, 'name' => 'Taiwan'],
                ['dialling_code' => 81, 'name' => 'Japan'],
                ['dialling_code' => 82, 'name' => 'South Korea'],
                ['dialling_code' => 84, 'name' => 'Vietnam'],
                ['dialling_code' => 86, 'name' => 'China'],
                ['dialling_code' => 90392, 'name' => 'Northern Cyprus'],
                ['dialling_code' => 961, 'name' => 'Lebanon'],
                ['dialling_code' => 963, 'name' => 'Syria'],
                ['dialling_code' => 964, 'name' => 'Iraq'],
                ['dialling_code' => 965, 'name' => 'Kuwait'],
                ['dialling_code' => 966, 'name' => 'Saudi Arabia'],
                ['dialling_code' => 967, 'name' => 'Yemen'],
                ['dialling_code' => 968, 'name' => 'Oman'],
                ['dialling_code' => 970, 'name' => 'Palestinian territories'],
                ['dialling_code' => 971, 'name' => 'United Arab Emirates'],
                ['dialling_code' => 972, 'name' => 'Israel'],
                ['dialling_code' => 973, 'name' => 'Bahrain'],
                ['dialling_code' => 974, 'name' => 'Qatar'],
                ['dialling_code' => 975, 'name' => 'Bhutan'],
                ['dialling_code' => 976, 'name' => 'Mongolia'],
                ['dialling_code' => 977, 'name' => 'Nepal'],
                ['dialling_code' => 992, 'name' => 'Tajikistan'],
                ['dialling_code' => 993, 'name' => 'Turkmenistan'],
                ['dialling_code' => 994, 'name' => 'Azerbaijan'],
                ['dialling_code' => 995, 'name' => 'Georgia'],
                ['dialling_code' => 996, 'name' => 'Kyrgyzstan'],
                ['dialling_code' => 998, 'name' => 'Uzbekistan'],
                ['dialling_code' => 91, 'name' => 'India'],
                ['dialling_code' => 92, 'name' => 'Pakistan'],
                ['dialling_code' => 93, 'name' => 'Afghanistan'],
                ['dialling_code' => 94, 'name' => 'Sri Lanka'],
                ['dialling_code' => 98, 'name' => 'Iran']
            ]
        );
    }
}
